### ISSUE TITLE
[レイアウト]セレクト画面のレイアウト作成

### ISSUE THREAD

**Issue by harumidiv** [inouefood/oh-natto#104]
## 概要
セレクト画面のレイアウトを作成する

**Comment by ch64ng** [comment]
#126

**Comment by ch64ng** [comment]
![sara](https://user-images.githubusercontent.com/27540771/99868650-ad5eda80-2c07-11eb-9553-4f26027a670a.png)
![negi_t](https://user-images.githubusercontent.com/27540771/99868659-b64fac00-2c07-11eb-81f6-7869e37b111d.png)
![okura_t](https://user-images.githubusercontent.com/27540771/99868662-b94a9c80-2c07-11eb-97ed-0c7ccdc263de.png)
![shirasu_t](https://user-images.githubusercontent.com/27540771/99868663-bbacf680-2c07-11eb-9268-6452736b251a.png)
