### ISSUE TITLE
[レイアウト]TotalEat画面のレイアウト作成

### ISSUE THREAD

**Issue by harumidiv** [inouefood/oh-natto#106]
## 概要
TotalEat画面のレイアウト作成

**Comment by harumidiv** [comment]
https://github.com/inouefood/oh-natto/issues/84

**Comment by harumidiv** [comment]
孤独な納豆:1000以下
納豆の村: 1000位上-3000以下
納豆の町: 3000以上-5000以下

**Comment by ch64ng** [comment]
画面の下の方にテキストで「あと3467粒で〇〇」みたいなのも表示したい

**Comment by harumidiv** [comment]
https://github.com/inouefood/oh-natto/pull/152

**Comment by ch64ng** [comment]
| 孤独 | 村 | 町 | 国？ |
| ---- | ---- | ---- | ---- |
| ![total_0](https://user-images.githubusercontent.com/27540771/101233703-04cb7300-36fd-11eb-994f-79ea3360f45d.png) | ![total_1](https://user-images.githubusercontent.com/27540771/101233736-4825e180-36fd-11eb-8ee4-dd4df9f02960.png) | ![total_2](https://user-images.githubusercontent.com/27540771/101233743-583dc100-36fd-11eb-8774-7bb191473b59.png) | ![total_3](https://user-images.githubusercontent.com/27540771/101233746-625fbf80-36fd-11eb-90ec-99c641155c42.png) |

**Comment by harumidiv** [comment]
https://github.com/inouefood/oh-natto/pull/160
